### PR TITLE
corona updates

### PR DESCRIPTION
**Pull request by giammi56**
I added some corrections to the minimum number of copied need for the submission.
I provided some useful information about the new procedures during Corona.
I will further update the defence section as soon as I have more info.

### CODE REVIEW

**Comment by giammi56** [comment]
A kind reminder from Frau Igelbrink about a signed "Datenschutzerklärung" for the treatment of personal data. The form is uploaded to the repo with a link to it in Procedures.

**Review by AxelKrypton — CHANGES_REQUESTED** [review]
Thanks @giammi56 for taking the time to update the files! Everything looks good to me, just one minor change I am not sure of,
```diff
- As one can see from the form, you need to appoint a chairman, as well as someone to write the PhD protocol.
+ As one can see from the form, you need to appoint a chairman, and someone how writes the PhD protocol.
```
I am not sure about _someone how_ and I would prefer _someone ~how~ that_ or _someone ~how~ which_.

I can approve this PR and than you can open another one if you need to change something else.

**Comment by giammi56** [comment]
Hi Alessandro,
I amended the "how" into "who", it was a typo, thank you for your remark. Thank you for maintaining this repo.
A friend from chemistry will soon add some details for the timing of the defence. He has been forced to postpone the defence of about 20 days. The reason is a rule which imposes a minimum of 10 days delay after the end of the circulation period to officially have the defence. He will hopefully add some details.

**Review by AxelKrypton — APPROVED** [review]

**Comment by AxelKrypton** [comment]
Thanks for fixing it! Indeed, _who_ is even better. :upside_down_face: I will merge the pull request in and I am happy to review more in the future. :muscle:

**Pull request merged**
